version: '2.2'
services:
  # elasticsearch  
  elasticsearch:
    image: 192.168.15.1:5000/elk-elasticsearch-ik:$ELK_VERSION
    container_name: elasticsearch
    restart: always
    environment: 
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml    
      - ./data:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
      - ./plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200     
      - 9300:9300 
    networks:
      elk:
        aliases:
          - elasticsearch
networks: 
  elk:
    driver: bridge
